services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html:cached
      - storage:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
      - vendor:/var/www/html/vendor
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  mysql:
    image: mysql:8.4
    container_name: mysql_laravel_factory
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel_project
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
  npm:
    image: node:23-alpine
    container_name: npm_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel_network

  composer:
    image: composer
    container_name: composer_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: artisan_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
    networks:
      - laravel_network
  
      
volumes:
  storage:
  bootstrap_cache:
  vendor:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge