services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html:cached
      - storage:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
      - vendor:/var/www/html/vendor
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    image: postgres
    container_name: postgres_laravel_factory
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network
  npm:
    image: node:23-alpine
    container_name: npm_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel_network

  composer:
    image: composer
    container_name: composer_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: artisan_laravel_factory
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - postgres
    networks:
      - laravel_network
  redis:
    image: redis/redis-stack
    container_name: redis_laravel_factory
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - laravel_network
  
      
volumes:
  storage:
  bootstrap_cache:
  vendor:
  redis_data:
  postgres_data:
    driver: local

networks:
  laravel_network:
    driver: bridge